[build]
builder = "nixpacks"
buildCommand = "pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[nixpacks]
python_version = "3.11" 